### PR TITLE
Improve the web experience for end user

### PR DESCRIPTION
**Pull request by curtis-bull**
Re-organized the web files
Implement Bootstrap UI
Minor fixes

### CODE REVIEW

**Comment by onebeartoe** [comment]
Curtis, I am trying to find a way to reach out to you offline, to discus the changes in this pull request.  If you have found out how to here, then can you send me a private message please?  Otherwise can you reach out to me on Google+?   My handle is onebeartoe there.

**Comment by curtis-bull** [comment]
It looks like GitHub removed private messaging.  Sent Google+ invite.

The file separator change came from the logic failure here: https://github.com/curtis-bull/PIXEL/blob/master/pixel-web-enabled/src/main/java/org/onebeartoe/web/enabled/pixel/controllers/StaticFileHttpHandler.java#L45

The file.getPath would return c:\users\user\pixel\, but the root variable would have pixel.getPixelHome();
with the value of c:\users\user/pixel/ so it would fail to properly load the root path ie (http://localhost:2007/) on a Windows computer.

**Comment by onebeartoe** [comment]
Does this mean you did see the app fail to properly load the application
root path, on the MS Windows platform?

**Comment by onebeartoe** [comment]
Curtis, I looked for your Google+ message, but did not see it in the
inbox.  Is there an other way to reach you?

**Comment by curtis-bull** [comment]
Sure, my email is curtis at oushi dot org

**Comment by curtis-bull** [comment]
Does this mean you did see the app fail to properly load the application
root path, on the MS Windows platform?
Yes, running the app on MS Windows.  The web browser would redirect with error 403 instead of displaying the page.

**Comment by onebeartoe** [comment]
Thanks for confirming.  I hadn't seen that error before.

**Pull request closed without merging**
