### PR TITLE
Fix typos and add command line parameter for the HTTP port

### PR DESCRIPTION
**Pull request by curtis-bull**

### CODE REVIEW

**Comment by onebeartoe** [comment]
This pull request is a good addition to the feature set.  

But, what about line 64 of CliPixel.java?  It has a call to System.exit().  

I'd like accept this pull request, but without the system exit calls.

Curtis, what do you think about removing the calls to System.exit()   ?

**Comment by curtis-bull** [comment]
Sure, I can remove it.  It will just skip the invalid parameter and run with the default port 2007.  Also, a person cannot print the help and not run the program.

**Comment by onebeartoe** [comment]
I am still new Github.  If it is a hassle to edit the pull request, then it
is cool.  I'll accept it as is, and remove the calls to System.exit().
Just let me know if you have already done it.  Thanks.

**Comment by curtis-bull** [comment]
Closing pull request to make a change.

**Pull request closed without merging**
